# Generated by Django 4.2.1 on 2023-06-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectodjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('contrasenia', models.IntegerField()),
                ('numFono', models.IntegerField()),
            ],
        ),
    ]
